Repository utkarsh006/Eazy-Android, pull requests merged in 2022-10, with the labels that each got.

#37 Added article related to layout and its types
  Articles/9_Layout_and_their_types.md
Labels: hacktoberfest, hacktoberfest-accepted

#42 Kotlin over java
  Articles/1_kotlin_over_java.md
Labels: hacktoberfest

#45 Improve layout article
  Articles/9_Layout_and_their_types.md
Labels: hacktoberfest

#44 Minor Kotlin vs Java formatting improvements
  Articles/1_kotlin_over_java.md
Labels: hacktoberfest

#49 Simplify readme
  README.md
Labels: hacktoberfest

#51 Fix typo and list in PR template
  .github/Pull_Request_Template.md
Labels: hacktoberfest

#48 please review for Article 7 : Code Components : Activities
  Articles/Article 7 : Code Components : Activities.md
Labels: hacktoberfest

#58 Create 5_Significance_Of_Manifest_File_in_Android
  Articles/5_Significance_of_Manifest_file_in_Android.md
Labels: hacktoberfest

#57 Create 12_Styles_and_Themes_in_Android.md
  Articles/12_Styles_and_Themes_in_Android.md
Labels: hacktoberfest, hacktoberfest-accepted, Merged 🎉

#61 Android Project Structure Added
  Articles/android_project_structure.md
Labels: hacktoberfest

#64 Files naming Convention Added
  Articles/14_android_files_naming_conventions.md
Labels: hacktoberfest
